map $http_user_agent $is_mobile {
    default 0;
    ~*(iphone|android|ipad|ipod|mobile) 1;
}

upstream desktop { server webtop:3000; }      # webtop écoute en 3000
upstream mobile  { server firefox_mobile:5800; } # jlesage écoute en 5800

server {
  listen 80;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location / {
    if ($is_mobile) { proxy_pass http://mobile; break; }
    proxy_pass http://desktop;
  }
}
